plugins:
  endorse_enabled:
    default: true
    client: true
  allow_endorsement_on_all_topics:
    default: true
    client: true
  endorsement_trust_level:
    default: 4
    client: true
  empty_circle_on_unendorsed:
    default: true
    client: true
  endorsed_quote_length:
    default: 300
    client: false
  endorsed_topics_auto_close_hours:
    default: 0
